//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::post_drafts::Entity as PostDrafts;
pub use super::post_versions::Entity as PostVersions;
pub use super::posts::Entity as Posts;
pub use super::users::Entity as Users;
