// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod rustpress {
  pub mod system {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod logging {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn log_info(message: &str,) -> (){
        unsafe {
          let vec0 = message;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "rustpress:system/logging")]
          unsafe extern "C" {
            #[link_name = "log-info"]
            fn wit_import1(_: *mut u8, _: usize, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, _: usize, ) { unreachable!() }
          wit_import1(ptr0.cast_mut(), len0);
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn log_warn(message: &str,) -> (){
        unsafe {
          let vec0 = message;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "rustpress:system/logging")]
          unsafe extern "C" {
            #[link_name = "log-warn"]
            fn wit_import1(_: *mut u8, _: usize, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, _: usize, ) { unreachable!() }
          wit_import1(ptr0.cast_mut(), len0);
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn log_error(message: &str,) -> (){
        unsafe {
          let vec0 = message;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "rustpress:system/logging")]
          unsafe extern "C" {
            #[link_name = "log-error"]
            fn wit_import1(_: *mut u8, _: usize, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, _: usize, ) { unreachable!() }
          wit_import1(ptr0.cast_mut(), len0);
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn log_debug(message: &str,) -> (){
        unsafe {
          let vec0 = message;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "rustpress:system/logging")]
          unsafe extern "C" {
            #[link_name = "log-debug"]
            fn wit_import1(_: *mut u8, _: usize, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, _: usize, ) { unreachable!() }
          wit_import1(ptr0.cast_mut(), len0);
        }
      }

    }

  }
}
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod rustpress {
    pub mod system {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod hooks {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        #[derive(Clone)]
        pub struct PostData {
          pub id: i64,
          pub title: _rt::String,
          pub content: _rt::String,
          pub category: _rt::String,
          pub author_id: i64,
          pub created_at: _rt::String,
          pub updated_at: _rt::String,
        }
        impl ::core::fmt::Debug for PostData {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("PostData").field("id", &self.id).field("title", &self.title).field("content", &self.content).field("category", &self.category).field("author-id", &self.author_id).field("created-at", &self.created_at).field("updated-at", &self.updated_at).finish()
          }
        }
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_on_post_published_cabi<T: Guest>(arg0: i64,arg1: *mut u8,arg2: usize,arg3: *mut u8,arg4: usize,arg5: *mut u8,arg6: usize,arg7: i64,arg8: *mut u8,arg9: usize,arg10: *mut u8,arg11: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result5 = {
          let len0 = arg2;
          let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
          let len1 = arg4;
          let bytes1 = _rt::Vec::from_raw_parts(arg3.cast(), len1, len1);
          let len2 = arg6;
          let bytes2 = _rt::Vec::from_raw_parts(arg5.cast(), len2, len2);
          let len3 = arg9;
          let bytes3 = _rt::Vec::from_raw_parts(arg8.cast(), len3, len3);
          let len4 = arg11;
          let bytes4 = _rt::Vec::from_raw_parts(arg10.cast(), len4, len4);
          T::on_post_published(PostData{
            id: arg0,
            title: _rt::string_lift(bytes0),
            content: _rt::string_lift(bytes1),
            category: _rt::string_lift(bytes2),
            author_id: arg7,
            created_at: _rt::string_lift(bytes3),
            updated_at: _rt::string_lift(bytes4),
          })
        };
        let ptr6 = (&raw mut _RET_AREA.0).cast::<u8>();
        match result5 {
          Ok(e) => { {
            *ptr6.add(0).cast::<u8>() = (0i32) as u8;
            let PostData{ id:id7, title:title7, content:content7, category:category7, author_id:author_id7, created_at:created_at7, updated_at:updated_at7, } = e;
            *ptr6.add(8).cast::<i64>() = _rt::as_i64(id7);
            let vec8 = (title7.into_bytes()).into_boxed_slice();
            let ptr8 = vec8.as_ptr().cast::<u8>();
            let len8 = vec8.len();
            ::core::mem::forget(vec8);
            *ptr6.add(16+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len8;
            *ptr6.add(16).cast::<*mut u8>() = ptr8.cast_mut();
            let vec9 = (content7.into_bytes()).into_boxed_slice();
            let ptr9 = vec9.as_ptr().cast::<u8>();
            let len9 = vec9.len();
            ::core::mem::forget(vec9);
            *ptr6.add(16+3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len9;
            *ptr6.add(16+2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr9.cast_mut();
            let vec10 = (category7.into_bytes()).into_boxed_slice();
            let ptr10 = vec10.as_ptr().cast::<u8>();
            let len10 = vec10.len();
            ::core::mem::forget(vec10);
            *ptr6.add(16+5*::core::mem::size_of::<*const u8>()).cast::<usize>() = len10;
            *ptr6.add(16+4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr10.cast_mut();
            *ptr6.add(16+6*::core::mem::size_of::<*const u8>()).cast::<i64>() = _rt::as_i64(author_id7);
            let vec11 = (created_at7.into_bytes()).into_boxed_slice();
            let ptr11 = vec11.as_ptr().cast::<u8>();
            let len11 = vec11.len();
            ::core::mem::forget(vec11);
            *ptr6.add(24+7*::core::mem::size_of::<*const u8>()).cast::<usize>() = len11;
            *ptr6.add(24+6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr11.cast_mut();
            let vec12 = (updated_at7.into_bytes()).into_boxed_slice();
            let ptr12 = vec12.as_ptr().cast::<u8>();
            let len12 = vec12.len();
            ::core::mem::forget(vec12);
            *ptr6.add(24+9*::core::mem::size_of::<*const u8>()).cast::<usize>() = len12;
            *ptr6.add(24+8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr12.cast_mut();
          } },
          Err(e) => { {
            *ptr6.add(0).cast::<u8>() = (1i32) as u8;
            let vec13 = (e.into_bytes()).into_boxed_slice();
            let ptr13 = vec13.as_ptr().cast::<u8>();
            let len13 = vec13.len();
            ::core::mem::forget(vec13);
            *ptr6.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>() = len13;
            *ptr6.add(8).cast::<*mut u8>() = ptr13.cast_mut();
          } },
        };ptr6
      } }
      #[doc(hidden)]
      #[allow(non_snake_case)]
      pub unsafe fn __post_return_on_post_published<T: Guest>(arg0: *mut u8,) { unsafe {
        let l0 = i32::from(*arg0.add(0).cast::<u8>());
        match l0 {
          0 => {
            let l1 = *arg0.add(16).cast::<*mut u8>();
            let l2 = *arg0.add(16+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
            let l3 = *arg0.add(16+2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l4 = *arg0.add(16+3*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l3, l4, 1);
            let l5 = *arg0.add(16+4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l6 = *arg0.add(16+5*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l5, l6, 1);
            let l7 = *arg0.add(24+6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l8 = *arg0.add(24+7*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l7, l8, 1);
            let l9 = *arg0.add(24+8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l10 = *arg0.add(24+9*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l9, l10, 1);
          },
          _ => {
            let l11 = *arg0.add(8).cast::<*mut u8>();
            let l12 = *arg0.add(8+1*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l11, l12, 1);
          },
        }
      } }
      pub trait Guest {
        #[allow(async_fn_in_trait)]
        fn on_post_published(post: PostData,) -> Result<PostData,_rt::String>;
      }
      #[doc(hidden)]

      macro_rules! __export_rustpress_system_hooks_cabi{
        ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

          #[unsafe(export_name = "rustpress:system/hooks#on-post-published")]
          unsafe extern "C" fn export_on_post_published(arg0: i64,arg1: *mut u8,arg2: usize,arg3: *mut u8,arg4: usize,arg5: *mut u8,arg6: usize,arg7: i64,arg8: *mut u8,arg9: usize,arg10: *mut u8,arg11: usize,) -> *mut u8 {
            unsafe { $($path_to_types)*::_export_on_post_published_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) }
          }
          #[unsafe(export_name = "cabi_post_rustpress:system/hooks#on-post-published")]
          unsafe extern "C" fn _post_return_on_post_published(arg0: *mut u8,) {
            unsafe { $($path_to_types)*::__post_return_on_post_published::<$ty>(arg0) }
          }
        };);
      }
      #[doc(hidden)]
      pub(crate) use __export_rustpress_system_hooks_cabi;

      #[repr(align(8))]
      struct _RetArea([::core::mem::MaybeUninit::<u8>; 24+10*::core::mem::size_of::<*const u8>()]);
      static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 24+10*::core::mem::size_of::<*const u8>()]);

    }

  }
}
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]
  pub use alloc_crate::string::String;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  pub use alloc_crate::vec::Vec;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  
  pub fn as_i64<T: AsI64>(t: T) -> i64 {
    t.as_i64()
  }

  pub trait AsI64 {
    fn as_i64(self) -> i64;
  }

  impl<'a, T: Copy + AsI64> AsI64 for &'a T {
    fn as_i64(self) -> i64 {
      (*self).as_i64()
    }
  }
  
  impl AsI64 for i64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  
  impl AsI64 for u64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  extern crate alloc as alloc_crate;
  pub use alloc_crate::alloc;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_plugin_world_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::rustpress::system::hooks::__export_rustpress_system_hooks_cabi!($ty with_types_in $($path_to_types_root)*::exports::rustpress::system::hooks);
  )
}
#[doc(inline)]
pub(crate) use __export_plugin_world_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.50.0:rustpress:system:plugin-world:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 423] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa4\x02\x01A\x02\x01\
A\x04\x01B\x05\x01@\x01\x07messages\x01\0\x04\0\x08log-info\x01\0\x04\0\x08log-w\
arn\x01\0\x04\0\x09log-error\x01\0\x04\0\x09log-debug\x01\0\x03\0\x18rustpress:s\
ystem/logging\x05\0\x01B\x05\x01r\x07\x02idx\x05titles\x07contents\x08categorys\x09\
author-idx\x0acreated-ats\x0aupdated-ats\x04\0\x09post-data\x03\0\0\x01j\x01\x01\
\x01s\x01@\x01\x04post\x01\0\x02\x04\0\x11on-post-published\x01\x03\x04\0\x16rus\
tpress:system/hooks\x05\x01\x04\0\x1drustpress:system/plugin-world\x04\0\x0b\x12\
\x01\0\x0cplugin-world\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-co\
mponent\x070.243.0\x10wit-bindgen-rust\x060.50.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

