pub mod logger;

wit_bindgen::generate!({
    world: "plugin-world",
    path: "../wit",
    pub_export_macro: true,
    export_macro_name: "wit_export",
});
pub use exports::rustpress::plugin::post_hooks::OnPostPublishedData;
pub use wit_bindgen;

pub trait RustpressPlugin {
    fn on_post_published(post: OnPostPublishedData) -> anyhow::Result<OnPostPublishedData> {
        Ok(post)
    }
}

#[macro_export]
macro_rules! export {
    ($plugin_type:ty) => {
        // 1. define the intermediate layer Wrapper
        struct WasmWrapper;

        // 2. implement the "strict" Guest interface generated by wit-bindgen
        // ⚠️ pay attention to the path: $crate::bindings::exports::rustpress::plugin::hooks
        impl $crate::exports::rustpress::plugin::post_hooks::Guest for WasmWrapper {
            fn on_post_published(
                post: $crate::exports::rustpress::plugin::post_hooks::OnPostPublishedData,
            ) -> Result<$crate::exports::rustpress::plugin::post_hooks::OnPostPublishedData, String>
            {
                $crate::logger::init();

                // 3. call the user's implementation (using the RustpressPlugin Trait)
                let result = <$plugin_type as $crate::RustpressPlugin>::on_post_published(post);
                result.map_err(|e| e.to_string())
            }
        }

        // 4. call the underlying export macro (that we renamed in bindings)
        $crate::wit_export!(WasmWrapper);
    };
}
